ALTER TABLE players
ADD COLUMN IF NOT EXISTS username TEXT,
ADD COLUMN IF NOT EXISTS attack INTEGER DEFAULT 10,
ADD COLUMN IF NOT EXISTS defense INTEGER DEFAULT 10,
ADD COLUMN IF NOT EXISTS speed INTEGER DEFAULT 10,
ADD COLUMN IF NOT EXISTS hp INTEGER DEFAULT 100,
ADD COLUMN IF NOT EXISTS max_hp INTEGER DEFAULT 100,
ADD COLUMN IF NOT EXISTS stamina INTEGER DEFAULT 100,
ADD COLUMN IF NOT EXISTS max_stamina INTEGER DEFAULT 100,
ADD COLUMN IF NOT EXISTS fruit TEXT,
ADD COLUMN IF NOT EXISTS fruit_mastery INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS observation_haki INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS armament_haki INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS conqueror_haki INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS bounty BIGINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS title TEXT DEFAULT 'Rookie',
ADD COLUMN IF NOT EXISTS island TEXT DEFAULT 'Foosha Village',
ADD COLUMN IF NOT EXISTS story_progress INTEGER DEFAULT 1;

CREATE TABLE IF NOT EXISTS player_fruit_storage
(
    discord_id BIGINT,
    fruit_id TEXT,
    obtained_at TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY(discord_id, fruit_id)
);

CREATE TABLE IF NOT EXISTS player_quests
(
    discord_id BIGINT,
    quest_id TEXT,
    progress INTEGER DEFAULT 0,
    required INTEGER DEFAULT 1,
    completed BOOLEAN DEFAULT FALSE,
    PRIMARY KEY(discord_id, quest_id)
);

CREATE TABLE IF NOT EXISTS boss_spawns
(
    boss TEXT PRIMARY KEY,
    island TEXT DEFAULT 'Foosha Village',
    alive BOOLEAN DEFAULT TRUE,
    spawned_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_players_fruit ON players(fruit);
CREATE INDEX IF NOT EXISTS idx_players_level ON players(level);
CREATE INDEX IF NOT EXISTS idx_fruit_storage_owner ON player_fruit_storage(discord_id);
